[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Example redirect configuration; however, Next.js middleware manages auth
[[redirects]]
  from = "/dashboard"
  to = "/auth/login"
  status = 307
  force = false

[[redirects]]
  from = "/permissions"
  to = "/auth/login"
  status = 307
  force = false

[[redirects]]
  from = "/roles"
  to = "/auth/login"
  status = 307
  force = false

[[redirects]]
  from = "/users"
  to = "/auth/login"
  status = 307
  force = false

[[redirects]]
  from = "/enquiries"
  to = "/auth/login"
  status = 307
  force = false

# Catch-all redirect to Next.js function for routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next-render"
  status = 200
