[[redirects]]
  from = "/dashboard"
  to = "/.netlify/functions/next_middleware"
  status = 200
  force = true

[[redirects]]
  from = "/permissions"
  to = "/.netlify/functions/next_middleware"
  status = 200
  force = true
